GET http://localhost:8000/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2l0dHkiLCJpYXQiOjE2OTY0MDMyOTN9.ZSbZeL-kuuRv_nTL54ukhZkNbfnNnZs9U30B3jSpXl0


###

POST http://localhost:8000/v1/users/register
Content-Type: application/json

{
    "name": "",
    "accessLevel": 4,
    "role": "",
    "phoneNumber": ""
}

###

POST http://localhost:8000/v1/users/password
Content-Type: application/json

{
    "id": "6519407fb9a891fce6e8e7d0",
    "password": "38108828",
    "rePassword": "38108828"
}